services:
  queue_events:
    container_name: queue_events_backend
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app:rw
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres_queue_events
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: queue_events
    ports:
      - 5432:5432
